spring:
  datasource:
    url: jdbc:postgres://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGSECRET}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop